#docker-compose file for local development 
version: "3.9"
services:
  app:
    build: .
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - ASPNETCORE_ENVIRONMENT=${ENVIRONMENT}
    ports:
      - "5001:80"
    links:
      - postgresql_db:${DB_HOST}
    depends_on:
      - postgresql_db
    volumes:
      - "app-data:/root/"
    deploy:
        resources:
            limits:
              memory: 256M
            reservations:
              memory: 128M
  postgresql_db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - PGPORT=${DB_PORT}
    ports:
      - "6011:${DB_PORT}"    
    restart: always
    volumes:
      - "database-data:/var/lib/postgresql/data/"
    
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${DB_USER}@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=${DB_PASSWORD}
    ports:
      - "5011:80"
    links:
      - postgresql_db:${DB_HOST}
    restart: always
    volumes:
      - "pgadmin:/root/.pgadmin"
      
volumes:
  app-data:
  database-data:
  pgadmin:
      
