version: "3.9"
services:
  app:
    #image: ghcr.io/daniilda/topcwbl:${VERSION_TAG}
    build: .
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - ASPNETCORE_ENVIRONMENT=${ENVIRONMENT}
    ports:
      - "5001:80"
    links:
      - postgresql_db:${DB_HOST}
    depends_on:
      - postgresql_db
  postgresql_db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    restart: always
    volumes:
      - "database-data:/var/lib/postgresql/data/"
    
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${DB_USER}@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=${DB_PASSWORD}
    ports:
      - "5011:80"
    links:
      - postgresql_db:${DB_HOST}
    restart: always
    volumes:
      - "pgadmin:/root/.pgadmin"
      
volumes:
  database-data:
  pgadmin:
      