name: Create Release

on: workflow_dispatch
  
jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: To lower case branch name
        shell: bash
        run: echo "##[set-output name=branchlower;]$(echo ${REF,,})"
        env:
          REF: steps.extract_branch.outputs.branch
        id: brach_lower
      - name: Create & Push release tag
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CUSTOM_TAG: ${{ steps.branch_lower.outputs.branch }}