name: Create Release

on: workflow_dispatch #change to PR closed
  
jobs:
  create-tag:
    runs-on: ubuntu-latest
    env: 
      TAG_NAME: _
    steps:
      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v5
      - name: To lowercase
        run: |
          TAG_NAME=$(echo ${{ steps.branch-name.outputs.current_branch }} | tr '[A-Z]' '[a-z]')
      - name: Create & Push release tag
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CUSTOM_TAG: ${{ env.TAG_NAME }}