name: release

on:
  pull_request:
    branches:
      - master
  push:
    tags:
      - dev-*
    branches:
      - master

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: topcwbl  # ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'
      - run: dotnet build
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'
      - run: dotnet test
  publish-docker-image:
    needs: [build, test]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to the registry
        uses: docker/login-action@master
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        uses: docker/metadata-action@master
        id: meta
        with:
          images: ${{ env.REGISTRY }}/${{ github.actor }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref, prefix=prerelease-, event=pr
            type=ref, event=tag
            type=ref, event=branch
            type=raw, value=prerelease-latest

      - name: Build and push Docker image
        uses: docker/build-push-action@master
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outouts.labels }}
          
  creating-release:
    if: github.event.pull_request.merged == 'true'
    needs: publish-docker-image
    runs-on: ubuntu-latest
    steps:
      - name: Create tag name
      uses: ASzc/change-string-case-action@v1
      id: string
      - with: 
          string: ${{ github.head_ref }}
      - name: Create & Push release tag
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        uses: anothrNick/github-tag-action@1.36.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CUSTOM_TAG: ${{ steps.string.outputs.lowercase }}
    